#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_PATH="$ROOT_DIR/docs/generated/project-facts.md"
CHECK=false

usage() {
  cat <<'EOF'
Usage: scripts/docs-facts.sh [--check] [--output <path>]

Generates factual project documentation extracted from Gradle and Kotlin source.
The output is intended as source material for AI-assisted documentation updates,
not as polished user documentation.

Options:
  --check         fail when the generated facts differ from the target file
  --output PATH   write to PATH instead of docs/generated/project-facts.md
  --help          show this help
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --check)
      CHECK=true
      shift
      ;;
    --output)
      shift
      OUTPUT_PATH="${1:-}"
      [[ -n "$OUTPUT_PATH" ]] || {
        echo "--output requires a path" >&2
        exit 2
      }
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

module_dir() {
  printf '%s' "$1" | tr ':' '/'
}

module_kind() {
  local module="$1"

  case "$module" in
    *rule-core)
      printf 'functional core'
      ;;
    *rule-json)
      printf 'serialization adapter'
      ;;
    *sdk*)
      printf 'sdk shell'
      ;;
    *api*)
      printf 'service shell'
      ;;
    *)
      printf 'module'
      ;;
  esac
}

dependency_lines() {
  local build_file="$1"

  if [[ ! -f "$build_file" ]]; then
    return 0
  fi

  awk '
    /^dependencies[[:space:]]*\{/ { in_deps = 1; depth = 1; next }
    in_deps {
      depth += gsub(/\{/, "{")
      depth -= gsub(/\}/, "}")
      if (depth <= 0) { in_deps = 0; next }
      line = $0
      sub(/^[[:space:]]+/, "", line)
      sub(/[[:space:]]+$/, "", line)
      if (line ~ /^(api|implementation|compileOnly|testImplementation|testRuntimeOnly)\(/) {
        print line
      }
    }
  ' "$build_file"
}

source_declarations() {
  local source_dir="$1"

  if [[ ! -d "$source_dir" ]]; then
    return 0
  fi

  find "$source_dir" -type f -name '*.kt' |
    sort |
    while IFS= read -r file; do
      awk -v file="$file" '
        /^[[:space:]]*private[[:space:]]+/ { next }
        /^[[:space:]]*(internal[[:space:]]+)?(sealed[[:space:]]+)?(data[[:space:]]+)?(object|class|interface|enum[[:space:]]+class|value[[:space:]]+class)[[:space:]]+[A-Za-z0-9_]+/ {
          line = $0
          sub(/^[[:space:]]+/, "", line)
          sub(/[({:].*$/, "", line)
          sub(/[[:space:]]+$/, "", line)
          sub(/^\.\//, "", file)
          print "- `" line "` (" file ")"
        }
      ' "$file"
    done
}

generate() {
  cd "$ROOT_DIR"

  modules=()
  while IFS= read -r module; do
    modules+=("$module")
  done < <(sed -n 's/^include("\(.*\)")/\1/p' settings.gradle.kts)

  cat <<'EOF'
# Project Facts

This file is generated by `scripts/docs-facts.sh`.
Use it as factual source material when updating human-authored documentation.

## Architecture Principles

- Functional core, imperative shell.
- Core rule evaluation is side-effect free.
- Value objects are preferred over primitive strings and numbers at domain boundaries.
- Important rule logic should prefer function composition and typed strategies over broad conditional branches.
- Rule identifiers use UUID v7.
- Canonical rule storage is expected to be JSON AST, with human-friendly file DSLs compiled into that format later.
- Mocking frameworks are avoided by default; use fakes, stubs, and real domain objects.
- Infrastructure tests should use real boundaries such as Testcontainers where practical.
- Tidy First is preferred for behavior-preserving structural improvements.
- Ktlint owns formatting; detekt should avoid duplicate formatting checks.
- Architecture checks can be added with ArchUnit once service, SDK, and adapter modules exist.

EOF

  echo "## Modules"
  echo
  for module in "${modules[@]}"; do
    printf -- '- `%s` (%s)\n' "$module" "$(module_kind "$module")"
  done
  echo

  echo "## Module Dependencies"
  echo
  for module in "${modules[@]}"; do
    local dir
    dir="$(module_dir "$module")"
    local deps
    deps="$(dependency_lines "$dir/build.gradle.kts")"
    [[ -n "$deps" ]] || continue
    echo "### \`$module\`"
    echo
    printf '%s\n' "$deps" | while IFS= read -r dep; do
      printf -- '- `%s`\n' "$dep"
    done
    echo
  done

  echo "## Kotlin Declarations"
  echo
  for module in "${modules[@]}"; do
    local dir
    dir="$(module_dir "$module")"
    local declarations
    declarations="$(source_declarations "$dir/src/main/kotlin")"
    [[ -n "$declarations" ]] || continue
    echo "### \`$module\`"
    echo
    printf '%s\n' "$declarations"
    echo
  done
}

tmp_file="$(mktemp)"
generate > "$tmp_file"

if [[ "$CHECK" == "true" ]]; then
  if [[ ! -f "$OUTPUT_PATH" ]]; then
    echo "Missing generated facts file: $OUTPUT_PATH" >&2
    rm -f "$tmp_file"
    exit 1
  fi

  if ! diff -u "$OUTPUT_PATH" "$tmp_file"; then
    echo "Generated documentation facts are out of date." >&2
    rm -f "$tmp_file"
    exit 1
  fi

  rm -f "$tmp_file"
  exit 0
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"
mv "$tmp_file" "$OUTPUT_PATH"
echo "Wrote $OUTPUT_PATH"
